name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (root)
        run: npm ci
      - name: Install backend dependencies
        run: npm ci
        working-directory: backend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps


      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Start backend server
        run: |
          cd backend
          nohup node server.js > ../backend.log 2>&1 &

      - name: Start frontend server
        run: nohup npm start > ../frontend.log 2>&1 &
        working-directory: frontend

      - name: Wait for backend to be ready
        run: |
          for i in {1..40}; do
            if nc -z localhost 4000; then echo Backend up; exit 0; fi
            sleep 1
          done
          echo "Backend did not start in time. Last 40 lines of backend.log:"
          tail -n 40 ./backend.log || echo "No backend.log found"
          exit 1

      - name: Wait for frontend to be ready
        run: |
          for i in {1..40}; do
            if nc -z localhost 3000; then echo Frontend up; exit 0; fi
            sleep 1
          done
          echo "Frontend did not start in time. Last 40 lines of frontend.log:"
          tail -n 40 ./frontend.log || echo "No frontend.log found"
          exit 1

      - name: Upload backend log
        uses: actions/upload-artifact@v4
        with:
          name: backend-log
          path: ./backend.log

      - name: Upload frontend log
        uses: actions/upload-artifact@v4
        with:
          name: frontend-log
          path: ./frontend.log

      - name: Run Playwright tests with Allure
        run: npm run test

      - name: Run frontend code coverage
        run: npm test -- --coverage --watchAll=false
        working-directory: frontend

      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

      - name: Run backend code coverage
        run: npm run coverage
        working-directory: backend

      - name: Upload backend coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage

      - name: Upload Playwright snapshots
        uses: actions/upload-artifact@v4
        with:
          name: playwright-snapshots
          path: tests/__screenshots__

      - name: Generate Allure report
        run: npm run allure:generate

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report
